- name: Deploy Ambari Cluster
  hosts: localhost
  gather_facts: no
  vars:
    ambari_user: admin
    ambari_pass: admin
    ambari_url: http://localhost:8080/api/v1
    blueprint_file: /root/blueprint.json
    vdf_file: /root/ODP-VDF.xml
    cluster_template_file: /root/cluster-template.json
    cluster_name: odp-cluster

  tasks:
  - name: Attempt Deployment
    block:
      - name: Run Deployment Tasks (First Attempt)
        include_tasks: deploy_tasks.yml
        vars:
          deploy_retries: 100

    rescue:
      - name: Deployment Failed - Starting Recovery Procedure
        debug:
          msg: "Deployment failed. Initiating cleanup and retry sequence..."

      - name: Stop Ambari Server
        shell: ambari-server stop
        ignore_errors: yes

      - name: Reset Ambari Server
        shell: ambari-server reset --silent
        ignore_errors: yes

      - name: Remove Phoenix PID file
        shell: rm -f /var/run/hbase/phoenix-hbase-queryserver.pid
        ignore_errors: yes

      - name: Run HDFS Corrections
        shell: /root/hdfscorrections.sh
        ignore_errors: yes

      - name: Run Hive Setup
        shell: /root/hivesetup.sh
        ignore_errors: yes

      - name: Ensure Ambari Server is started
        shell: ambari-server start
        ignore_errors: yes

      - name: Run Deployment Tasks (Retry after Reset)
        include_tasks: deploy_tasks.yml
        vars:
          deploy_retries: 120

