- name: Deploy Ambari Cluster
  hosts: localhost
  gather_facts: no
  vars:
    ambari_user: admin
    ambari_pass: admin
    ambari_url: http://localhost:8080/api/v1
    blueprint_file: /root/blueprint.json
    vdf_file: /root/ODP-VDF.xml
    cluster_template_file: /root/cluster-template.json
    cluster_name: odp-cluster

  tasks:
  - name: Wait for Ambari Server to be ready
    uri:
      url: "{{ ambari_url }}/check"
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      return_content: no
    register: ambari_check
    until: ambari_check.status == 200
    retries: 30
    delay: 10
    ignore_errors: yes

  - name: Wait for all 4 hosts to be registered
    uri:
      url: "{{ ambari_url }}/hosts"
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      return_content: yes
    register: hosts_response
    until: hosts_response.status == 200 and (hosts_response.content | from_json)['items'] | length == 4
    retries: 60
    delay: 10
    ignore_errors: yes

  - name: Register VDF
    uri:
      url: "{{ ambari_url }}/version_definitions"
      method: POST
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      body:
        VersionDefinition:
          version_url: "file://{{ vdf_file }}"
      body_format: json
      status_code: [ 201, 409, 500 ]
    register: vdf_result
    failed_when: vdf_result.status == 500 and "already defined" not in vdf_result.json.message

  - name: Register Blueprint
    uri:
      url: "{{ ambari_url }}/blueprints/odp-blueprint?validate_topology=false"
      method: POST
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      body: "{{ lookup('file', blueprint_file) }}"
      body_format: json
      status_code: [ 201, 409 ]

  - name: Check if Cluster already exists
    uri:
      url: "{{ ambari_url }}/clusters/{{ cluster_name }}"
      method: GET
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      status_code: [ 200, 404 ]
      return_content: no
    register: cluster_check

  - name: Create Cluster
    uri:
      url: "{{ ambari_url }}/clusters/{{ cluster_name }}"
      method: POST
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      body: "{{ lookup('file', cluster_template_file) }}"
      body_format: json
      status_code: 202
    register: cluster_request
    when: cluster_check.status == 404

  - name: Monitor Cluster Creation
    uri:
      url: "{{ cluster_request.json.href }}"
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      return_content: yes
    register: request_status
    until: (request_status.content | from_json).Requests.request_status == 'COMPLETED' or (request_status.content | from_json).Requests.request_status == 'FAILED'
    retries: 360
    delay: 10
    when: cluster_request.status == 202

  - name: Fail if cluster creation failed
    fail:
      msg: "Cluster creation failed. Check Ambari logs."
    when: cluster_request.status == 202 and (request_status.content | from_json).Requests.request_status == 'FAILED'
