- name: Deploy Ambari Cluster
  hosts: localhost
  gather_facts: no
  vars:
    ambari_user: admin
    ambari_pass: admin
    ambari_url: http://localhost:8080/api/v1
    blueprint_file: /root/blueprint.json
    vdf_file: /root/ODP-VDF.xml
    cluster_template_file: /root/cluster-template.json
    cluster_name: odp-cluster

  tasks:
  - name: Wait for all 4 hosts to be registered
    uri:
      url: "{{ ambari_url }}/hosts"
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      return_content: yes
    register: hosts_response
    until: hosts_response.json.items | length == 4
    retries: 60
    delay: 10

  - name: Register VDF
    uri:
      url: "{{ ambari_url }}/version_definitions"
      method: POST
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      body:
        VersionDefinition:
          version_url: "file://{{ vdf_file }}"
      body_format: json
      status_code: [ 201, 409 ]
    register: vdf_result
    failed_when: vdf_result.status != 201 and vdf_result.status != 409

  - name: Register Blueprint
    uri:
      url: "{{ ambari_url }}/blueprints/odp-blueprint"
      method: POST
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      body: "{{ lookup('file', blueprint_file) }}"
      body_format: json
      status_code: [ 201, 409 ]

  - name: Create Cluster
    uri:
      url: "{{ ambari_url }}/clusters/{{ cluster_name }}"
      method: POST
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      body: "{{ lookup('file', cluster_template_file) }}"
      body_format: json
      status_code: 202
    register: cluster_request
    ignore_errors: yes

  - name: Monitor Cluster Creation
    uri:
      url: "{{ cluster_request.json.href }}"
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      return_content: yes
    register: request_status
    until: request_status.json.Requests.request_status == 'COMPLETED' or request_status.json.Requests.request_status == 'FAILED'
    retries: 360
    delay: 10
    when: cluster_request.status == 202

  - name: Fail if cluster creation failed
    fail:
      msg: "Cluster creation failed. Check Ambari logs."
    when: cluster_request.status == 202 and request_status.json.Requests.request_status == 'FAILED'
