- name: Deploy Ambari Cluster
  hosts: localhost
  gather_facts: no
  vars:
    ambari_user: admin
    ambari_pass: admin
    ambari_url: http://localhost:8080/api/v1
    blueprint_file: /root/blueprint.json
    vdf_file: /root/ODP-VDF.xml
    cluster_template_file: /root/cluster-template.json
    cluster_name: odp-cluster

  tasks:
  - name: Wait for Ambari Server to be ready
    uri:
      url: "{{ ambari_url }}/check"
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      return_content: no
    register: ambari_check
    until: ambari_check.status == 200
    retries: 30
    delay: 10
    ignore_errors: yes

  - name: Wait for all 4 hosts to be registered
    uri:
      url: "{{ ambari_url }}/hosts"
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      return_content: yes
    register: hosts_response
    until: hosts_response.status == 200 and (hosts_response.content | from_json)['items'] | length == 4
    retries: 60
    delay: 10
    ignore_errors: yes

  - name: Delete existing Cluster
    uri:
      url: "{{ ambari_url }}/clusters/{{ cluster_name }}"
      method: DELETE
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      status_code: [ 200, 202, 404 ]

  - name: Wait for Cluster to be deleted
    uri:
      url: "{{ ambari_url }}/clusters/{{ cluster_name }}"
      method: GET
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      status_code: [ 404 ]
    register: cluster_gone
    until: cluster_gone.status == 404
    retries: 60
    delay: 5

  - name: Register VDF
    uri:
      url: "{{ ambari_url }}/version_definitions"
      method: POST
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      body:
        VersionDefinition:
          version_url: "file://{{ vdf_file }}"
      body_format: json
      status_code: [ 201, 409, 500 ]
    register: vdf_registration
    failed_when: vdf_registration.status != 201 and "Duplicate" not in vdf_registration.json.message|default("") and vdf_registration.status != 500

  - name: Delete existing Blueprint
    uri:
      url: "{{ ambari_url }}/blueprints/odp-blueprint"
      method: DELETE
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      status_code: [200, 404]

  - name: Register Blueprint
    uri:
      url: "{{ ambari_url }}/blueprints/odp-blueprint?validate_topology=false"
      method: POST
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      body: "{{ lookup('file', blueprint_file) }}"
      body_format: json
      status_code: [ 201, 409 ]


  - name: Create Cluster
    uri:
      url: "{{ ambari_url }}/clusters/{{ cluster_name }}"
      method: POST
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      body: "{{ lookup('file', cluster_template_file) }}"
      body_format: json
      status_code: 202
    register: cluster_request

  - name: Log request href for monitoring
    debug:
      msg: "Cluster Request HREF: {{ cluster_request.json.href }}"
    when: cluster_request.status == 202


  - name: Monitor Cluster Creation
    uri:
      url: "{{ cluster_request.json.href }}"
      user: "{{ ambari_user }}"
      password: "{{ ambari_pass }}"
      force_basic_auth: yes
      headers:
        X-Requested-By: "ambari"
      return_content: yes
    register: request_status
    until: (request_status.content | from_json).Requests.request_status == 'COMPLETED' or (request_status.content | from_json).Requests.request_status == 'FAILED'
    retries: 360
    delay: 30
    when: cluster_request.status == 202

  - name: Handle Cluster Creation Failure
    block:
      - name: Fail if status is failed (to trigger rescue)
        fail:
          msg: "Cluster creation failed initially."
        when: cluster_request.status == 202 and (request_status.content | from_json).Requests.request_status == 'FAILED'

    rescue:
      - name: Attempting Auto-Fix for HDFS Upload (OOM workaround)
        shell: sh /root/hdfscorrections.sh
        delegate_to: master.cdp
        register: hdfs_fix
        failed_when: false

      - name: Show fallback stdout
        debug:
          var: hdfs_fix.stdout
        when: hdfs_fix is defined

      - name: Show fallback stderr
        debug:
          var: hdfs_fix.stderr
        when: hdfs_fix is defined

      - name: Collect failure details (request and tasks)
        uri:
          url: "{{ ambari_url }}/clusters/{{ cluster_name }}/requests/{{ (request_status.content | from_json).Requests.id }}?fields=Requests/*,tasks/Tasks/command_detail,tasks/Tasks/status,tasks/Tasks/host_name,tasks/Tasks/stderr"
          user: "{{ ambari_user }}"
          password: "{{ ambari_pass }}"
          force_basic_auth: yes
          headers:
            X-Requested-By: "ambari"
          return_content: yes
        register: failure_dump
        ignore_errors: yes

      - name: Persist failure dump to file
        copy:
          dest: "/var/log/ansible/ambari-request-{{ (request_status.content | from_json).Requests.id }}.json"
          content: "{{ failure_dump.content | default('') }}"
        when: failure_dump is defined and failure_dump.content is defined

      - name: List all cluster requests
        uri:
          url: "{{ ambari_url }}/clusters/{{ cluster_name }}/requests?fields=Requests/request_status&to=9999"
          user: "{{ ambari_user }}"
          password: "{{ ambari_pass }}"
          force_basic_auth: yes
          headers:
            X-Requested-By: "ambari"
          return_content: yes
        register: all_reqs

      - name: Build list of active request IDs
        set_fact:
          active_request_ids: "{{ all_reqs.json.items | selectattr('Requests.request_status','in',['IN_PROGRESS','PENDING','QUEUED']) | map(attribute='Requests.id') | list }}"

      - name: Abort active requests
        uri:
          url: "{{ ambari_url }}/clusters/{{ cluster_name }}/requests/{{ item }}"
          method: PUT
          user: "{{ ambari_user }}"
          password: "{{ ambari_pass }}"
          force_basic_auth: yes
          headers:
            X-Requested-By: "ambari"
          body:
            Requests:
              request_status: "ABORTED"
          body_format: json
          status_code: [200, 202, 409]
        loop: "{{ active_request_ids | default([]) }}"
        loop_control:
          label: "request {{ item }}"

      - name: Stop all services (set to INSTALLED)
        uri:
          url: "{{ ambari_url }}/clusters/{{ cluster_name }}/services"
          method: PUT
          user: "{{ ambari_user }}"
          password: "{{ ambari_pass }}"
          force_basic_auth: yes
          headers:
            X-Requested-By: "ambari"
          body:
            RequestInfo:
              context: "Stop All Services"
            Body:
              ServiceInfo:
                state: "INSTALLED"
          body_format: json
          status_code: [200, 202, 409]
        register: stop_req
        failed_when: false

      - name: Wait until all services are INSTALLED
        uri:
          url: "{{ ambari_url }}/clusters/{{ cluster_name }}/services?fields=ServiceInfo/state"
          user: "{{ ambari_user }}"
          password: "{{ ambari_pass }}"
          force_basic_auth: yes
          headers:
            X-Requested-By: "ambari"
        register: svc_states
        until: svc_states.json.items | map(attribute='ServiceInfo.state') | list | unique == ['INSTALLED']
        retries: 60
        delay: 10
        failed_when: false

      - name: Delete existing Cluster (after cleanup)
        uri:
          url: "{{ ambari_url }}/clusters/{{ cluster_name }}"
          method: DELETE
          user: "{{ ambari_user }}"
          password: "{{ ambari_pass }}"
          force_basic_auth: yes
          headers:
            X-Requested-By: "ambari"
          status_code: [200, 202, 404]

      - name: Wait for Cluster to be deleted
        uri:
          url: "{{ ambari_url }}/clusters/{{ cluster_name }}"
          method: GET
          user: "{{ ambari_user }}"
          password: "{{ ambari_pass }}"
          force_basic_auth: yes
          headers:
            X-Requested-By: "ambari"
          status_code: [404]
        register: cluster_gone_after_fix
        until: cluster_gone_after_fix.status == 404
        retries: 60
        delay: 5

      - name: Re-Create Cluster (new request after fix)
        uri:
          url: "{{ ambari_url }}/clusters/{{ cluster_name }}"
          method: POST
          user: "{{ ambari_user }}"
          password: "{{ ambari_pass }}"
          force_basic_auth: yes
          headers:
            X-Requested-By: "ambari"
          body: "{{ lookup('file', cluster_template_file) }}"
          body_format: json
          status_code: 202
        register: cluster_request_retry

      - name: Monitor Retried Cluster Creation
        uri:
          url: "{{ cluster_request_retry.json.href }}"
          user: "{{ ambari_user }}"
          password: "{{ ambari_pass }}"
          force_basic_auth: yes
          headers:
            X-Requested-By: "ambari"
          return_content: yes
        register: retry_status
        until: (retry_status.content | from_json).Requests.request_status in ['COMPLETED','FAILED']
        retries: 360
        delay: 30

      - name: Fail if retry deployment failed
        fail:
          msg: "Cluster creation failed even after cleanup+recreate. Confira Ambari logs e /var/log/ansible/ambari-request-*.json."
        when: (retry_status.content | from_json).Requests.request_status == 'FAILED'
