---
- name: Common config for all nodes
  hosts: all
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Ensure python3 exists on targets (raw bootstrap)
      ansible.builtin.raw: |
        test -x /usr/bin/python3 || (command -v dnf >/dev/null && sudo dnf -y install python3 || sudo yum -y install python3)
      changed_when: false
  vars:
    hosts_lines:
      - "10.0.0.2   master.cdp"
      - "10.0.0.3   node1.cdp"
      - "10.0.0.4   node2.cdp"
      - "10.0.0.5   node3.cdp"
  tasks:
    - name: Disable SELinux (runtime)
      command: setenforce 0
      failed_when: false
      changed_when: false

    - name: Ensure SELinux disabled persistently
      ansible.builtin.replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=disabled'

    - name: Stop and disable firewalld
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Ensure packages present
      ansible.builtin.yum:
        name:
          - curl
          - unzip
          - tar
          - wget
          - sed
          - gcc
          - openssl-devel
          - openssl
          - krb5-workstation
          - krb5-libs
          - python3
          - java-1.8.0-openjdk-devel
          - snappy
          - openssh-server
          - openssh-clients
        state: present
        update_cache: yes

    - name: Ensure chronyd enabled and running
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes

    - name: Ensure /etc/hosts has cluster FQDNs
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {% for line in hosts_lines %}
          {{ line }}
          {% endfor %}
        marker: "# {mark} CDP_CLUSTER_HOSTS"

- name: Ambari repos and agent on all nodes
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Import Jenkins GPG key (used by repo)
      ansible.builtin.get_url:
        url: https://clemlabs.s3.eu-west-3.amazonaws.com/RPM-GPG-KEY-SHA256-Jenkins
        dest: /tmp/RPM-GPG-KEY-SHA256-Jenkins
    - name: rpm --import jenkins gpg key
      ansible.builtin.command: rpm --import /tmp/RPM-GPG-KEY-SHA256-Jenkins
      changed_when: false

    - name: Install ODP repo
      ansible.builtin.get_url:
        url: https://clemlabs.s3.eu-west-3.amazonaws.com/centos9-aarch64/odp-release/1.2.2.0-128/odp.repo
        dest: /etc/yum.repos.d/odp.repo

    - name: Install Ambari repo
      ansible.builtin.get_url:
        url: https://clemlabs.s3.eu-west-3.amazonaws.com/centos9-aarch64/ambari-release/2.7.9.0.0-61/ambari.repo
        dest: /etc/yum.repos.d/ambari.repo

    - name: Update packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install ambari-agent (all nodes)
      ansible.builtin.yum:
        name: ambari-agent.aarch64
        state: present

- name: Configure master node
  hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: Install server deps
      ansible.builtin.yum:
        name:
          - odp-select.aarch64
          - ambari-server.aarch64
          - postgresql-server
          - postgresql-contrib
        state: present

    - name: Initialize PostgreSQL if needed
      ansible.builtin.shell: |
        if [ ! -d /var/lib/pgsql/data/base ]; then
          postgresql-setup --initdb || true
        fi
      args:
        executable: /bin/bash

    - name: Ambari server setup (non-interactive)
      ansible.builtin.command:
        argv: ["ambari-server", "setup", "-s", "-j", "/usr/lib/jvm/java-1.8.0-openjdk"]
      register: ambari_setup
      changed_when: ambari_setup.rc == 0
      failed_when: ambari_setup.rc not in [0]

    - name: Start ambari-server
      ansible.builtin.service:
        name: ambari-server
        state: started
        enabled: yes

    - name: Start ambari-agent (master)
      ansible.builtin.service:
        name: ambari-agent
        state: started
        enabled: yes

    - name: Create console user and set password
      ansible.builtin.user:
        name: console
        groups: wheel
        append: yes
        state: present
    - name: Set console password
      ansible.builtin.shell: echo 'console:1aB@2bC#' | chpasswd

    - name: Append environment variables to root .bashrc
      ansible.builtin.blockinfile:
        path: /root/.bashrc
        marker: "# {mark} ODP_EXPORTS"
        block: |
          export ZOOKEEPER_HOME="/usr/odp/1.2.2.0-128/zookeeper"
          export PATH=$PATH:$ZOOKEEPER_HOME/bin
          export KAFKA_HOME="/usr/odp/1.2.2.0-128/kafka"
          export PATH=$PATH:$KAFKA_HOME/bin
          export NIFI_HOME="/usr/odp/1.2.2.0-128/nifi"
          export PATH=$PATH:$NIFI_HOME/bin
          export SPARK_HOME="/usr/odp/1.2.2.0-128/spark3"
          export PATH=$PATH:$SPARK_HOME/bin
          export HIVE_HOME="/usr/odp/1.2.2.0-128/hive"
          export PATH=$PATH:$HIVE_HOME/bin

    - name: Create hdfscorrections.sh
      ansible.builtin.copy:
        dest: /root/hdfscorrections.sh
        mode: '0755'
        content: |
          #!/bin/bash
          ambari-server stop
          sudo -u hdfs hdfs dfs -chown root:root /odp/apps/1.2.2.0-128/hbase
          sudo -u hdfs hdfs dfs -chmod 755 /odp/apps/1.2.2.0-128/hbase
          sudo -u hdfs hdfs dfs -put /var/lib/ambari-agent/tmp/yarn-ats/1.2.2.0-128/hbase.tar.gz /odp/apps/1.2.2.0-128/hbase/
          sudo -u hdfs hdfs dfs -chmod 555 /odp/apps/1.2.2.0-128/hbase
          ambari-server restart

    - name: Download MySQL connector (yum package missing on OL9)
      ansible.builtin.get_url:
        url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.28/mysql-connector-java-8.0.28.jar
        dest: /usr/share/java/mysql-connector-java.jar
        mode: '0644'

    - name: Ensure MySQL connector in Ambari resources
      ansible.builtin.copy:
        src: /usr/share/java/mysql-connector-java.jar
        dest: /var/lib/ambari-server/resources/mysql-connector-java.jar
        remote_src: yes
        mode: '0644'

    - name: Setup Ambari to use MySQL JDBC driver
      ansible.builtin.command: ambari-server setup --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar
      changed_when: false

    - name: Restart Ambari Server to pick up changes
      ansible.builtin.service:
        name: ambari-server
        state: restarted

- name: Configure workers
  hosts: workers
  become: yes
  gather_facts: false
  tasks:
    - name: Install odp-select and ambari-agent
      ansible.builtin.yum:
        name:
          - odp-select.aarch64
          - ambari-agent.aarch64
        state: present

    - name: Point ambari-agent to master
      ansible.builtin.lineinfile:
        path: /etc/ambari-agent/conf/ambari-agent.ini
        regexp: '^hostname='
        line: 'hostname=master.cdp'
        create: yes

    - name: Reload systemd to recognize ambari-agent init script
      ansible.builtin.command: systemctl daemon-reload
      changed_when: false

    - name: Ensure ambari-agent is running and enabled
      ansible.builtin.service:
        name: ambari-agent
        state: started
        enabled: yes
